Vagrant.configure("2") do |config|

  # Define web01
  config.vm.define "web01" do |web01|
    web01.vm.box = "centos/stream9"
    web01.vm.hostname = "web01.local"
    web01.vm.network "private_network", ip: "192.168.56.10"

    web01.vm.provider "virtualbox" do |vb|
      vb.name = "web01"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Define web02
  config.vm.define "web02" do |web02|
    web02.vm.box = "centos/stream9"
    web02.vm.hostname = "web02.local"
    web02.vm.network "private_network", ip: "192.168.56.11"

    web02.vm.provider "virtualbox" do |vb|
      vb.name = "web02"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  # Define db01
  config.vm.define "db01" do |db01|
    db01.vm.box = "ubuntu/jammy64"
    db01.vm.hostname = "db01.local"
    db01.vm.network "private_network", ip: "192.168.56.12"

    db01.vm.provider "virtualbox" do |vb|
      vb.name = "db01"
      vb.memory = 1024
      vb.cpus = 1
    end
  end

end
