apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-wordpress-secret
type: Opaque
data:
  mysql-root-password: {{ .Values.secrets.mysqlRootPassword }}
  mysql-database: {{ .Values.secrets.mysqlDatabase }}
  mysql-user: {{ .Values.secrets.mysqlUser }}
  mysql-password: {{ .Values.secrets.mysqlPassword }}