apiVersion: v1
kind: Secret
metadata:
  name: mysql-wordpress-secret
type: Opaque
data:
  mysql-root-password: cm9vdHBhc3N3b3Jk  # rootpassword
  mysql-database: d29yZHByZXNz  # wordpress
  mysql-user: d3B1c2Vy  # wpuser
  mysql-password: d3BwYXNzd29yZA==  # wppassword